- name: "Install workstation"
  hosts: localhost
  connection: local
  roles:
    - external_repo
    - firmware-update
    - base_packages
    - ffmpeg-swapping
    - zsh
    - vscode
    - browser
    - rclone
    # - balena-etcher
    - autoremove_unused_packages