- name: "Install workstation"
  hosts: localhost
  connection: local
  #become: 'yes'
  roles:
    # - ansible-galaxy
    - role: robertdebock.bootstrap
      become: yes
    - role: robertdebock.epel
      become: yes
    - role: robertdebock.rpmfusion
      become: yes
    - base_packages
    - zsh
    - vscode
    - browser
    - skype4linux
    #- balena-etcher
    - autoremove_unused_packages
    # - ms-font