- name: "Install workstation"
  hosts: localhost
  connection: local
  roles:
    - external_repo
    - base_packages
    - zsh
    - vscode
    - browser
    - rclone
    # - skype4linux
    # - balena-etcher
    - autoremove_unused_packages