- name: "Install workstation"
  hosts: localhost
  connection: local
  vars:
    user_name: "{{ ansible_user_id }}"
    user_home: "{{ ansible_env.HOME }}"

  roles:
    - external_repo
    - firmware-update
    - base_packages
    - ffmpeg-swapping
    - zsh
    - vscode
    - browser
    - rclone
    # - balena-etcher
    - autoremove_unused_packages