- name: "Install workstation"
  hosts: localhost
  connection: local
  roles:
    - external_repo
    - base_packages
    - zsh
    - vscode
    - browser
    - skype4linux
    - balena-etcher
    - autoremove_unused_packages

- name: Unconditionally reboot the machine with all defaults
  ansible.builtin.reboot: