- name: "Install workstation"
  hosts: localhost
  connection: local
  become: true
  vars:
    user_name: "{{ ansible_facts['user_id'] }}"
    user_home: "{{ ansible_facts['env']['HOME'] }}"

  roles:
    - external_repo
    - firmware-update
    - fix-hw-conf
    - base_packages
    - ffmpeg-swapping
    - zsh
    - vscode
    - browser
    - rclone
    # - balena-etcher
    - autoremove_unused_packages