- name: "Install workstation"
  hosts: localhost
  connection: local
  #become: 'yes'
  roles:
    - role: robertdebock.bootstrap
      become: yes
    - role: robertdebock.epel
    become: yes
    #- role: robertdebock.rpmfusion
    #become: yes
    - gnome-tweak-tool
    #- vlc
    - zsh
    - tilix