- name: "Install workstation"
  hosts: localhost
  connection: local
  #become: 'yes'
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.epel
    #- role: robertdebock.rpmfusion
    - gnome-tweak-tool
    #- vlc
    - zsh
    - tilix