---
- name: Getting rpm kew
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: dnf update
  become: true
  shell: dnf update


- name: Install vscode
  become: true
  dnf: 
    name: code
    state: present
