---
- name: Getting rpm kew
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: check vscore yum repo exists
  stat:
    path: /etc/yum.repos.d/vscode.repo
  register: stat_vscode_repo

- name: Copy vscode repo
  copy: 
    src: ../files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
  when: not stat_vscode_repo.stat.result.exists

- name: Install vscode
  become: true
  dnf: 
    name: code
    state: present
