- name: Install Balena Etcher repo
  get_url: 
    url: https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh
    dest: /tmp
    mode: a+x

- name: Install Balena Etcher
  become: yes
  dnf: 
    name: "/tmp/setup.rpm.sh"
    state: present

- name: Remove Balena Etcher install file
  file:
    state: absent
    path: "/tmp/setup.rpm.sh"