- name: Install Balena Etcher repo
  become: yes
  get_url: 
    url: https://balena.io/etcher/static/etcher-rpm.repo
    dest: /etc/yum.repos.d/etcher-rpm.repo

- name: Install Balena Etcher
  become: yes
  dnf: 
    name: balena-etcher-electron
    state: present
