- name: Install Balena Etcher repo
  get_url: 
    url: https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh
    dest: /tmp
    mode: a+x
    register: geturl_return_value

- debug:
  var: geturl_return_value

- name: Install Balena Etcher
  become: yes
  ansible.builtin.command: /tmp/balena-etcher_rpm.sh

- name: Remove Balena Etcher install file
  file:
    state: absent
    path: /tmp/balena-etcher_rpm.sh