- name: Install Balena Etcher repo
  get_url: 
    url: https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh
    dest: /tmp
    mode: a+x
  register: geturl_return_value

- name: Install Balena Etcher
  become: yes
  ansible.builtin.command: "{{ geturl_return_value.dest }}"
  register: install_etcher

- debug:
    var: install_etcher

- name: Remove Balena Etcher install file
  file:
    state: absent
    path: "{{ geturl_return_value.dest }}"