---
  
- name: get Vivaldi repo 
  become: yes 
  command: dnf config-manager addrepo --from-repofile=https://repo.vivaldi.com/archive/vivaldi-fedora.repo

- name: Install Vivaldi browser
  become: yes
  dnf:
    name: vivaldi-stable
    state: present
    disable_gpg_check: true

# - name: install Google Chrome repository
#   become: yes
#   command: dnf config-manager --set-enabled google-chrome

- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present

- name: get Opera repo 
  become: yes 
  command: dnf config-manager addrepo  --id=opera-browser --set=name='Opera Browser packages' --set=baseurl='https://rpm.opera.com/rpm' --set=gpgkey='https://rpm.opera.com/rpmrepo.key'

- name: Install Opera browser
  become: yes
  dnf:
    name: opera-stable
    state: present
    disable_gpg_check: true

- name: get Brave browser repo
  become: yes
  command: dnf config-manager addrepo  --id=brave-browser --set=name='Brave Browser' --set=baseurl='https://rpm.opera.com/rpm' --set=gpgkey='https://rpm.opera.com/rpmrepo.key'
  dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

- name: get Brave browser key
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

- name: Install Brave
  become: yes
  dnf:
    name: brave-browser
    state: present

