---
  
- name: get Vivaldi repo 
  become: yes 
  command: dnf config-manager --add-repo https://repo.vivaldi.com/archive/vivaldi-fedora.repo

- name: get Opera repo 
  become: yes 
  command: dnf config-manager --add-repo https://rpm.opera.com/rpm

- name: install Google Chrome repository
  become: yes
  command: dnf config-manager --set-enabled google-chrome

- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present

- name: Install Opera browser
  become: yes
  dnf:
    name: opera-stable
    state: present
    disable_gpg_check: true


- name: Install Vivaldi browser
  become: yes
  dnf:
    name: vivaldi-stable
    state: present
    disable_gpg_check: true
