---
  
- name: Scarica il file del repository ufficiale di Vivaldi
  ansible.builtin.get_url:
    url: https://repo.vivaldi.com/stable/vivaldi-fedora.repo
    dest: /etc/yum.repos.d/vivaldi-fedora.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts['distribution'] == 'Fedora'

- name: Installa il browser Vivaldi stabile
  ansible.builtin.dnf:
    name: vivaldi-stable
    state: present
  when: ansible_facts['distribution'] == 'Fedora'


- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present

- name: Import Opera GPG key
  ansible.builtin.rpm_key:
    key: https://rpm.opera.com/rpmrepo.key
    state: present

- name: Add Opera RPM repository
  ansible.builtin.yum_repository:
    name: opera
    description: Opera packages
    baseurl: https://rpm.opera.com/rpm
    gpgcheck: true
    gpgkey: https://rpm.opera.com/rpmrepo.key
    enabled: true

- name: Install Opera Stable package
  ansible.builtin.dnf:
    name: opera-stable
    state: present

- name: Import Brave GPG key
  ansible.builtin.rpm_key:
    key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    state: present

- name: Add Brave RPM repository
  ansible.builtin.yum_repository:
    name: brave-browser
    description: Brave Browser Release Channel
    baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/
    gpgcheck: true
    gpgkey: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    enabled: true

- name: Install Brave Browser package
  ansible.builtin.dnf:
    name: brave-browser
    state: present
