- name: Check Opera repo exists
  stat:
    path: /etc/yum.repos.d/opera.repo
  register: stat_opera_repo

- name: Copy Opera repo
  become: yes
  copy: 
    src: ../files/opera.repo
    dest: /etc/yum.repos.d/opera.repo
  when: not stat_opera_repo.stat.exists
  
- name: get Vivaldi repo 
  become: yes 
  command: dnf config-manager --add-repo https://repo.vivaldi.com/archive/vivaldi-fedora.repo

- name: install Google Chrome repository
  become: yes
  command: dnf config-manager --set-enabled google-chrome

- name: Install Google Chrome
  become: yes
  dnf:
    name: google-chrome-stable
    state: present

- name: Install Opera browser
  become: yes
  dnf:
    name: opera-stable
    state: present

- name: Install Vivaldi browser
  become: yes
  dnf:
    name: vivaldi-stable
    state: present