---
- name: Enable RPM Fusion Free
  become: true
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm
    state: present